name: Build macOS App

# main ブランチへのプッシュ or PR のたびに走る
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1) コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Python をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) pip キャッシュ（高速化）
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) 依存ライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5) （任意）テストを実行
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # 6) PyInstaller でビルド
      - name: Build with PyInstaller
        run: |
          pyinstaller \
            --windowed \
            --name OthelloGame \
            main.py

      # 7) ビルド成果物をアーティファクトとしてアップロード
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: OthelloGame-macos
          path: dist/OthelloGame

      # 8) itch.io CLI (butler) をインストール
      - name: Install itch.io Butler CLI
        run: |
          curl -L https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default/file.tar.gz \
            | tar xz butler
          sudo mv butler /usr/local/bin/
          sudo chmod +x /usr/local/bin/butler

      # 9) Authenticate Butler
      - name: Authenticate Butler
        env:
          ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
        run: |
          butler login --api-key "$ITCHIO_API_KEY"
